In [3]:
import numpy as np

In [1]:
a = [1, 2, 3]

In [1]:
def calc(a,b,c):
    if (a.isnumeric() == True) and (c.isnumeric() == True) :
        a = int(a)
        c = int(c)
        if b == 'x' :
            print('Hasil dari', a, b, c, 'adalah', a*c)
        elif b == '+' :
            print('Hasil dari', a, b, c, 'adalah', a+c)
        elif b == ':' :
            print('Hasil dari', a, b, c, 'adalah', a/c)
        elif b == "-" :
            print('Hasil dari', a, b, c, 'adalah', a - c)
        elif b == "^" :
            print('Hasil dari', a, b, c, 'adalah', a**c)
        else :
            print('operator', b, 'tidak ditemukan')
    else :
        print('salah')

a = (input('masukkan angka1= '))
b = (input('masukkan operator= '))
c = (input('masukkan angka2= '))

calc(a,b,c)

masukkan angka1=  10
masukkan operator=  -
masukkan angka2=  10


Hasil dari 10 - 10 adalah 0


## Indexing & slicing 

In [2]:
array_1 = [1,2,3,4,5,6,7,8,9.10]
array_1[3:]

[4, 5, 6, 7, 8, 9.1]

In [5]:
import numpy as np
array_3 = np.array([[1,2,3,4]])
array_4 = np.array([[5,6,7,8]])
array_3.shape

(1, 4)

In [6]:
#np.newaxis
array_4 = np.array([4,5,6])
array_4[np.newaxis]
print(array_4[:,np.newaxis].shape)

(3, 1)


In [10]:
array_5 = np.array([1,2,3,4,5])
array_6 = np.array([5,6,7,8])
np.hstack([array_5,array_6])

array([1, 2, 3, 4, 5, 5, 6, 7, 8])

In [12]:
array_7 = np.array([3,4,5,6,7,8,9])
array_8 = np.expand_dims(array_7,axis=1)
array_9 = np.expand_dims(array_7,axis=0)
print(array_8)
print(array_8.shape)
print(array_9)
print(array_9.shape)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(7, 1)
[[3 4 5 6 7 8 9]]
(1, 7)


In [13]:
array_7 = np.array([3,4,5,6,7,8,9])
array_7+2

array([ 5,  6,  7,  8,  9, 10, 11])

In [14]:
array_7*2

array([ 6,  8, 10, 12, 14, 16, 18])

In [16]:
array_10 = np.array([[1,2,3],[4,5,6]])
array_10-4

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [4]:
c = np.array([1,2,3,4,3,2,1,5,6,7,8,9,10])
d = np.zeros((2,2))
#ndim
print(c.ndim)
print(d.ndim)

#size
print(c.size)
print(d.size)

#reshape
print(c[:-1].reshape(3,4))

1
2
13
4
[[1 2 3 4]
 [3 2 1 5]
 [6 7 8 9]]


## Filtering Array

In [21]:
array_7 = np.array([3,4,5,6,7,8,9])
print(array_7[array_7>5])
print(array_7[array_7==5])
print(array_7[array_7<=4])

[6 7 8 9]
[5]
[3 4]


In [33]:
def bintang(baris):
    kolom = baris *2 -1
    spasi = 0
    hasil = ""
    for i in range(baris):
        for j in range(spasi):
            hasil += " "
        for j in range(kolom):
            if i == 0:
                simbol = "*"
            elif i == baris -1:
                simbol =  "*"
            elif j == 0 or j == kolom -1 :
                simbol = "*"
            else :
                simbol = "*"
            hasil += simbol
        kolom -= 2
        spasi += 1
        if baris ==1 :
            hasil += ""
        else:
            hasil += "\n"
    baris = baris -1
    kolom = 3
    spasi = baris -1
    for i in range(baris):
        for j in range(spasi):
            hasil += " "
        for j in range(kolom):
            if j == 0 or j == kolom -1:
                simbol = "*"
            elif i == baris -1:
                simbol = "*"
            else :
                simbol = "*"
            hasil += simbol
        kolom += 2
        spasi -= 1
        if i != baris -1:
            hasil += "\n"
        else :
            hasil+=""
    return hasil
ok = int(input("How Tall?  "))
print (bintang(ok))

How Tall?  8
***************
 *************
  ***********
   *********
    *******
     *****
      ***
       *
      ***
     *****
    *******
   *********
  ***********
 *************
***************


## hstack, vstack, hsplit, vsplit

In [35]:
#stack
array_14 = np.array([3,4,5,6,7])
array_15 = np.array([7,8,9,10,11])
print('secara vertikal')
print(np.vstack([array_14,array_15]))
print('secara horizontal')
print(np.hstack([array_14,array_15]))

secara vertikal
[[ 3  4  5  6  7]
 [ 7  8  9 10 11]]
secara horizontal
[ 3  4  5  6  7  7  8  9 10 11]


In [37]:
#split
array_16 = np.array([3,4,5,6,7,8])
array_split = np.hsplit(array_16,2)
(array_split)

[array([3, 4, 5]), array([6, 7, 8])]

In [39]:
#vsplit
array_19 = np.array([[1,2,3,4],[4,5,6,7]])
print(array_19)
print('horizontal split')
print(np.hsplit(array_19,2))
print('vertikal split')
print(np.vsplit(array_19,2))

[[1 2 3 4]
 [4 5 6 7]]
horizontal split
[array([[1, 2],
       [4, 5]]), array([[3, 4],
       [6, 7]])]
vertikal split
[array([[1, 2, 3, 4]]), array([[4, 5, 6, 7]])]


In [42]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
print(array_a+array_b)

[4 6 8]


In [45]:
array_c = np.array([[1,2,3],[4,5,6]])
array_d = np.array([[6,7,8],[9,10,11]])
print(array_c-array_d)

[[-5 -5 -5]
 [-5 -5 -5]]


In [48]:
print(array_a.max())
print(array_c.max())
print(array_c)
print(array_c.max(axis=0))
print(array_c.min(axis=0))

3
6
[[1 2 3]
 [4 5 6]]
[4 5 6]
[1 2 3]


## Transpos

In [51]:
array_e = np.array([[5,2,3],[4,5,6]])
print(array_e)
print(array_e.shape)
print(array_e.T.shape)

[[5 2 3]
 [4 5 6]]
(2, 3)
(3, 2)


In [52]:
print(array_e.T)
print(array_e.T.shape)

[[5 4]
 [2 5]
 [3 6]]
(3, 2)


In [55]:
array_random = np.random.random([3,2])*100
print(array_random)

[[ 9.51722358 53.13713176]
 [51.08884177  4.96295303]
 [39.45369824  1.08565146]]


In [56]:
array_random = np.random.random([3,2])*100
print(array_random)
print(array_random.flatten())

[[98.01470218 54.29348205]
 [76.68514769 33.83400419]
 [12.30354401 31.97523121]]
[98.01470218 54.29348205 76.68514769 33.83400419 12.30354401 31.97523121]


## Numpy Math Formulas

In [58]:
array_random = np.random.random([3,2])*100
print(array_random)
np.sum(array_random)

[[24.2394126  68.84511559]
 [93.69407489 30.96441768]
 [33.06532154  2.2435325 ]]


253.05187480159302

In [59]:
np.square(9)

81

In [60]:
np.sqrt(9)

3.0

In [61]:
a = np.log(1000000)
print(a)

13.815510557964274


In [6]:
np.empty((2,2))

array([[2.12199579e-314, 0.00000000e+000],
       [5.37543423e-321, 3.79442416e-321]])

In [62]:
np.exp(a)

999999.9999999995

## Prime Number Generator Based on Interval


In [76]:
angka_awal = int(input('Masukan angka awal: '))
angka_akhir = int(input('Masukan angka akhir: '))
 
list_angka = [i for i in range(angka_awal, angka_akhir +1 )]
 
bilangan_prima = []
for i in list_angka:
    if (i==2 or i==3 or i==5 or i==7) or (i%2 != 0 and i%3 != 0 and i%5 != 0 and i%7 != 0):
        bilangan_prima.append(i)
 
print(bilangan_prima)

Masukan angka awal: 1
Masukan angka akhir: 10
[1, 2, 3, 5, 7]


In [80]:
# Quis 3

lower_limit = int(input('lower limit : '))
upper_limit = int(input('upper limit : '))
print(lower_limit,'sampai', upper_limit) 
for num in range(lower_limit,upper_limit+1):
    if num > 1:
        for i in range(2,num):
            if (num%i)==0:
                break
        else:
            print(num)

lower limit : 10
upper limit : 20
10 sampai 20
11
13
17
19


## Operasi Arimatik antar 2 Array


In [5]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
array_c = np.array([[5,2,3],[4,5,6]])
print(array_a.max())
print(array_c.max())
print(array_c)
print(array_c.max(axis=0))
print(array_c.min(axis=0))

3
6
[[5 2 3]
 [4 5 6]]
[5 5 6]
[4 2 3]
